---
abstract: 'unique symbols'
author:
  - 'Neil Bowers <neil@bowers.com>'
build_requires:
  Data::Dumper: 0
  Storable: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.008, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: constant-Atom
requires:
  Carp: 0
  base: 0
  overload: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  homepage: https://github.com/neilbowers/constant-Atom
  repository: https://github.com/neilbowers/constant-Atom.git
version: 0.07
