---
abstract: 'unique symbols'
author:
  - 'This module was originally created by Jonathan R. Warden E<lt>john@newchester.comE<gt>,'
  - 'but is currently being maintained by Neil Bowers E<lt>neilb@cpan.orgE<gt>.'
build_requires: {}
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4007, CPAN::Meta::Converter version 2.132620'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: constant-Atom
provides:
  constant::Atom:
    file: lib/constant/Atom.pm
    version: 0.06
  constant::Atom::Strict:
    file: lib/constant/Atom/Strict.pm
    version: 0.06
resources:
  license: http://dev.perl.org/licenses/
  repository: https://github.com/neilbowers/constant-Atom
version: 0.06
